# Generated by Django 3.1.4 on 2021-01-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoritySignRequiredForProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=225)),
                ('address_of_authority_for_sign', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'AuthoritySignRequiredForProof',
                'verbose_name_plural': 'AuthoritySignRequiredForProofs',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequiredForProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=225)),
            ],
            options={
                'verbose_name': 'DocumentRequiredForProof',
                'verbose_name_plural': 'DocumentRequiredForProofs',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=225)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ProcessForDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='for eg. adhaar card doc process', max_length=225)),
            ],
            options={
                'verbose_name': 'ProcessForDoc',
                'verbose_name_plural': 'ProcessForDocs',
            },
        ),
        migrations.CreateModel(
            name='ProofCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=220)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ProofCategories',
                'verbose_name_plural': 'ProofCategoriess',
            },
        ),
        migrations.CreateModel(
            name='StepOfProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_desc', models.TextField()),
            ],
            options={
                'verbose_name': 'StepOfProcess',
                'verbose_name_plural': 'StepOfProcesss',
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=225)),
                ('description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='documents/img')),
                ('belonging_state', models.CharField(choices=[('1', 'Please Select'), ('2', 'Andra Pradesh'), ('3', 'Arunachal Pradesh'), ('4', 'Assam'), ('5', 'Bihar'), ('6', 'Chhattisgarh'), ('7', 'Chandigarh'), ('8', 'Dadar and Nagar Haveli'), ('9', 'Daman and Diu'), ('10', 'Delhi'), ('11', 'Goa'), ('12', 'Gujarat'), ('13', 'Haryana'), ('14', 'Himachal Pradesh'), ('15', 'Jammu and Kashmir'), ('16', 'Jharkhand'), ('17', 'Karnataka'), ('18', 'Kerala'), ('19', 'Lakshadeep'), ('20', 'Madya Pradesh'), ('21', 'Maharashtra'), ('22', 'Manipur'), ('23', 'Meghalaya'), ('24', 'Mizoram'), ('25', 'Nagaland'), ('26', 'Orissa'), ('27', 'Punjab'), ('28', 'Pondicherry'), ('29', 'Rajasthan'), ('30', 'Sikkim'), ('31', 'Tamil Nadu'), ('32', 'Telagana'), ('33', 'Tripura'), ('34', 'Uttaranchal'), ('35', 'Uttar Pradesh'), ('36', 'West Bengal'), ('37', 'Andaman and Nicobar Island')], default='', max_length=255)),
                ('authority_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_api.authoritysignrequiredforproof')),
                ('documents_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_api.documentrequiredforproof')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_api.processfordoc')),
            ],
            options={
                'verbose_name': 'Proof',
                'verbose_name_plural': 'Proofs',
            },
        ),
        migrations.AddField(
            model_name='processfordoc',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_api.stepofprocess'),
        ),
    ]
