# Generated by Django 3.1.4 on 2021-01-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authoritysignrequiredforproof',
            options={'verbose_name': 'AuthoritySignRequiredForProof', 'verbose_name_plural': 'Authority Signs Required For Proofs'},
        ),
        migrations.AlterModelOptions(
            name='documentrequiredforproof',
            options={'verbose_name': 'DocumentRequiredForProof', 'verbose_name_plural': 'List of document required for proofs'},
        ),
        migrations.AlterModelOptions(
            name='processfordoc',
            options={'verbose_name': 'ProcessForDoc', 'verbose_name_plural': 'Process for documents'},
        ),
        migrations.AlterModelOptions(
            name='proofcategories',
            options={'verbose_name': 'ProofCategories', 'verbose_name_plural': 'Proof Categories'},
        ),
        migrations.AlterModelOptions(
            name='stepofprocess',
            options={'verbose_name': 'StepOfProcess', 'verbose_name_plural': 'Step of Processs'},
        ),
    ]
